### ISSUE TITLE
Error during the process

### ISSUE THREAD

**Issue by mirismaili** [nfriend/google-translate-xlf#3]
Thank useful tool. But it can't:

```
> translate-xlf -i messages.xlf -o messages.hi.xlf -f en -t hi
X Something went wrong while translating messages.xlf!
Error
    at C:\Users\I\AppData\Roaming\npm\node_modules\google-translate-xlf\node_modules\google-translate-api\index.js:105:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

`messages.xlf` is: 
https://raw.githubusercontent.com/nfriend/google-translate-xlf/master/examples/messages.xlf

I also tested with some other files.

OS: Widnows 10 x64

**Comment by kevplx** [comment]
@mirismaili Did u make any break-through on this? I am having same issue. Or did u find an alternate way of auto translating the xlf file?

**Comment by joldibaev** [comment]
> @mirismaili Did u make any break-through on this? I am having same issue. Or did u find an alternate way of auto translating the xlf file?

I also got this error, then using 'console.log' I found out that it gives the error 'too many requests' and just rebooted the router (changed the IP).

**Comment by mirismaili** [comment]
> @mirismaili Did u make any break-through on this? I am having same issue. Or did u find an alternate way of auto translating the xlf file?

I'm sorry, I'm late!

Unfortunately no. 

(I had forgotten this issue!)

**Comment by kevplx** [comment]
No problem.
